name: manage-azure-policy-c1c6e3d6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_License_-_Append_hybrid_use_benefit_c12c5a43-7fa5-4e54-9a88-fb61e7a3a580/**'
#      - .github/workflows/manage-azure-policy-c1c6e3d6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c1c6e3d6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_License_-_Append_hybrid_use_benefit_c12c5a43-7fa5-4e54-9a88-fb61e7a3a580/**
